baseURL = "https://caiusball.com/"
languageCode = "en-us"
title = "Gonville and Caius May Ball"
theme = "mayball2021"
removePathAccents = true



# HTML before the closing </head>
[params]
customHead = ""

# Navigation
[params.navigation]
logo = "/images/logo-gc.png"
home = "Home"
about = "About"
service = "Our Team"
contact = "Contact Us"

# Hero Area
[params.hero]
enable            = true
bg                = "/images/header-bg.jpg"
title             ="" # "BRING YOUR PRODUCT TO LIGHT"
subtitle          ="" # "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna"
btnText           ="" # "Get Started"

# counter
disableCountdown  = true
countdownYear = "2022"
countdownMonth = "6"
countdownDay  = "21"

# About Section
[params.about]
enable      = true
heading     = "About the Gonville and Caius May Ball"
description = "The Gonville and Caius May Ball is a lavish and sought-after event held in June to celebrate the end of the year. Spanning the whole of the College, the Caius May Ball is an all-inclusive experience where the best drink, food, music and entertainment in Cambridge will be on display for you to enjoy. Join us on the 21st of June 2022 for the return of the Gonville and Caius May Ball, sure to be a night you’ll never forget."

#[[params.about.sliderItem]]
#image   = "/images/about/1.jpg"
#[[params.about.sliderItem]]
#image   = "/images/about/2.jpg"
#[[params.about.sliderItem]]
#image   = "/images/about/3.jpg"
#[[params.about.sliderItem]]
#image   = "/images/about/2.jpg"

# Access Section
[params.access]
enable      = true
heading     = "Accessibility Pledge"
description = "We pledge to [Insert Pledge Here]"

#[[params.about.sliderItem]]
#image   = "/images/about/1.jpg"
#[[params.about.sliderItem]]
#image   = "/images/about/2.jpg"
#[[params.about.sliderItem]]
#image   = "/images/about/3.jpg"
#[[params.about.sliderItem]]
#image   = "/images/about/2.jpg"

# Service Section
[params.service]
enable      = true
title       = "Meet Our Committee"
subtitle    = ""#"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et"

#[[params.service.serviceItem]]
# give icon(themefisher icon font), title, description
# more about themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
#icon    = "tf-strategy"
#title   = "President"
#description = "Floris Blok"
#email = "mayball.president@cai.cam.ac.uk"
#delay   = "0s"

#[[params.service.serviceItem]]
# give icon(themefisher icon font), title, description
# more about themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
#icon    = "tf-circle-compass"
#title   = "VP"
#description = "Binu Perera"
#email = "mayball.vicepresident@cai.cam.ac.uk"
#delay   = "0.2s"

[[params.service.serviceItem]]
# give icon(themefisher icon font), title, description
# more about themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
icon    = "tf-anchor2"
title   = "Treasurer"
description = "Edouard Barrier"
email = "mayball.juniortreasurer@cai.cam.ac.uk"
delay   = "0s"

[[params.service.serviceItem]]
# give icon(themefisher icon font), title, description
# more about themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
icon    = "tf-circle-compass"
title   = "Head of Ops"
description = "Rosanna Mutsaars"
email = "mayball.headofoperations@cai.cam.ac.uk"
delay   = "0s"

[[params.service.serviceItem]]
# give icon(themefisher icon font), title, description
# more about themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
icon    = "tf-anchor2"
title   = "Creative Director"
description = "Emma Bryan"
email = "mayball.creativedirector@cai.cam.ac.uk"
delay   = "0s"

[[params.service.serviceItem]]
# give icon(themefisher icon font), title, description
# more about themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
icon    = "tf-globe"
title   = "Staff"
description = "Aysha Iqbal"
email = "mayball.headofstaff@cai.cam.ac.uk"
delay   = "0s"

#[[params.service.serviceItem]]
# give icon(themefisher icon font), title, description
# more about themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
#icon    = "tf-strategy"
#title   = "Secretary"
#description = "Arjun Sharma"
#email = "mayball.secretary@cai.cam.ac.uk"
#delay   = "0s"

[[params.service.serviceItem]]
# give icon(themefisher icon font), title, description
# more about themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
icon    = "tf-globe"
title   = "Creative"
description = "Audrey Lee"
email = "mayball.creative@cai.cam.ac.uk"
delay   = "0s"

[[params.service.serviceItem]]
# give icon(themefisher icon font), title, description
# more about themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
icon    = "tf-strategy"
title   = "Creative"
description = "Parth Shimpi"
email = "mayball.creative@cai.cam.ac.uk"
delay   = "0s"

[[params.service.serviceItem]]
# give icon(themefisher icon font), title, description
# more about themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
icon    = "tf-circle-compass"
title   = "Logistics"
description = "M. Richards"
email = "mayball.operations@cai.cam.ac.uk"
delay   = "0s"

[[params.service.serviceItem]]
# give icon(themefisher icon font), title, description
# more about themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
icon    = "tf-anchor2"
title   = "Logistics"
description = "Owain Bates"
email = "mayball.operations@cai.cam.ac.uk"
delay   = "0s"

[[params.service.serviceItem]]
# give icon(themefisher icon font), title, description
# more about themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
icon    = "tf-globe"
title   = "Publicity"
description = "Scarlett Pitt"
email = "mayball.publicity@cai.cam.ac.uk"
delay   = "0s"

[[params.service.serviceItem]]
# give icon(themefisher icon font), title, description
# more about themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
icon    = "tf-strategy"
title   = "Web"
description = "William Qin"
email = "mayball.web@cai.cam.ac.uk"
delay   = "0s"

[[params.service.serviceItem]]
# give icon(themefisher icon font), title, description
# more about themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
icon    = "tf-circle-compass"
title   = "Musical Ents"
description = "Stan MacMurray"
email = "mayball.ents@cai.cam.ac.uk"
delay   = "0s"

[[params.service.serviceItem]]
# give icon(themefisher icon font), title, description
# more about themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
icon    = "tf-globe"
title   = "Non-musical Ents"
description = "Emily Herbert"
email = "mayball.ents@cai.cam.ac.uk"
delay   = "0s"

[[params.service.serviceItem]]
# give icon(themefisher icon font), title, description
# more about themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
icon    = "tf-anchor2"
title   = "Food"
description = "Kate Aspbury"
email = "mayball.food@cai.cam.ac.uk"
delay   = "0s"

[[params.service.serviceItem]]
# give icon(themefisher icon font), title, description
# more about themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
icon    = "tf-strategy"
title   = "Drink"
description = "Alexandria Smith"
email = "mayball.drinks@cai.cam.ac.uk"
delay   = "0s"

[[params.service.serviceItem]]
# give icon(themefisher icon font), title, description
# more about themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
icon    = "tf-circle-compass"
title   = "Ticketing"
description = "Vanessa Chen"
email = "mayball.ticketing@cai.cam.ac.uk"
delay   = "0s"

[[params.service.serviceItem]]
# give icon(themefisher icon font), title, description
# more about themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
icon    = "tf-anchor2"
title   = "Technical"
description = "Javier Sanchez-Bonilla Martinez"
email = "mayball.technical@cai.cam.ac.uk"
delay   = "0s"

# Call to Action Section
[params.cta]
enable      = true
bg          = "/images/call-to-action.jpg"
title       = "Media Enquiries"
subtitle    = "For media enquiries, please email "
baseURL = "master--quirky-blackwell-88a617.netlify.app"

[params.contact]
enable      = true
title       = "Vendors/Sponsors"
subtitle    = "Are you interested in being a Vendor? "
subtitle2    = "Are you interested in being a Sponsor? "


[params.contactven]
enable      = true
title       = "Vendors"
subtitle    = "Are you interested in being a Vendor? Fill out this form and we'll get back to you soon!"

[params.contactspon]
enable      = true
title       = "Sponsorship opportunities"

[[params.contactspon.stline]]
line = "The Gonville & Caius May Ball is one of the showpiece events of the Cambridge social calendar, gathering over a thousand students in the gorgeous setting of the Caius Old Courts. The event runs all through the night, with unlimited food, drink, activities, music and dancing for all our guests, be they students or alumni."
bold = "normal"

[[params.contactspon.stline]]
line = "To create the highest quality ball possible for the most affordable price, we naturally seek out sponsors to partner with. There are four tiers of sponsorship available, although bespoke arrangements are very possible. In all cases you would have access to a huge community of talented, ambitious individuals."
bold = "normal"

[[params.contactspon.stline]]
line = "Platinum - details to be discussed on a case by case basis"
size = "20px"
bold = "bold"

[[params.contactspon.stline]]
line = "All the benefits of Bronze, Silver and Gold, plus:"
bold = "normal"

[[params.contactspon.stline]]
line = "- longer term relationship possibilities e.g. running promotional schemes in the lead up to the event and following the event"
bold = "normal"

[[params.contactspon.stline]]
line = "- And other bespoke arrangements"
bold = "normal"
 

[[params.contactspon.stline]]
line = " Gold - £4000"
size = "20px"
bold = "bold"

[[params.contactspon.stline]]
line = "All the benefits of bronze and silver, plus:"
bold = "normal"

[[params.contactspon.stline]]
line = "- logo added to event wristband (another keepsake that is provided for guests to identify them on the night, made out of fabric like a festival wristband) "
bold = "normal"

[[params.contactspon.stline]]
line = "- Ability to promote through our mailing list "
bold = "normal"

[[params.contactspon.stline]]
line = "- increased visibility on the night of the ball, through a dedicated stall/brand advertising"
bold = "normal"

[[params.contactspon.stline]]
line = "- Allocation of 6 tickets for purchase if desired"
bold = "normal"

[[params.contactspon.stline]]
line = "Silver - £2000"
size = "20px"
bold = "bold"

[[params.contactspon.stline]]
line = "All the benefits of Bronze tier, plus:"
bold = "normal"

[[params.contactspon.stline]]
line = "- Full page advert in event programme "
bold = "normal"

[[params.contactspon.stline]]
line = "- Logo featured in the ‘post ball video’"
bold = "normal"

[[params.contactspon.stline]]
line = "- Allocation of 4 tickets for purchase if desired"
bold = "normal"

[[params.contactspon.stline]]
line = "Bronze - £1000"
size = "20px"
bold = "bold"

[[params.contactspon.stline]]
line = "- Logo on website "
bold = "normal"

[[params.contactspon.stline]]
line = "- 1/2 page advert in event programme (well produced keepsake that is handed out prior to the night of the ball) "
bold = "normal"

[[params.contactspon.stline]]
line = "- Logo and announcement of partnership on social media "
bold = "normal"


[[params.contactspon.stline]]
line = "- Allocation of 2 tickets for purchase if desired"
bold = "normal"



[[params.contactspon.stline]]
line = "Either fill out this form and await a response, or contact us directly at mayball.juniortreasurer@cai.cam.ac.uk."
bold = "normal"